import store from "@/store";
import fram from "@/assets/fram.png";
import { computed, watch } from "vue";

let layerResult = null;
let editableLayerList = computed(() => {
  return store.state.menu.layerLists;
});
watch(
  editableLayerList,
  (newValue, oldValue) => {
    layerResult = newValue;
  },
  { immediate: true, deep: true }
);
// 此处定义buttonGroup组名（key为组名，值为Symbol）
const buttonGroupKeys = {
  group1: 0,
  editAddGroup: 1,
  measureGroup: 2,
  mapToolGroup: 3,
  RotatingGroup: 4,
  plottingGroup: 5,
  onlineMeasureGroup: 6,
};

const config = [
  // {
  //   name: "数据",
  //   icon: "",
  //   type: "page",
  //   groups: [
  //     {
  //       name: "离线数据源",
  //       icon: "",
  //       type: "group",
  //       items: [
  //         {
  //           name: "GSF",
  //           icon: "icon-16gl-folderOpen",
  //           type: "button",
  //           tip: "GSF简介",
  //           enable: true,
  //           checked: false,
  //           buttonGroup: buttonGroupKeys.group1,
  //           command: "ZoomToCommand", // 执行一个功能
  //           lib: "ExamplePlugin",
  //           paramter: {
  //             zoom: 12,
  //           },
  //         },
  //         {
  //           name: "SHP",
  //           icon: "icon-baocun",
  //           type: "button",
  //           enable: true,
  //           checked: false,
  //           buttonGroup: buttonGroupKeys.group1,
  //           command: "OpenWidgetCommand", // 打开一个组件
  //           lib: "WidgetPlugin",
  //           paramter: {
  //             styles: "bottom:20px;right:20px;",
  //             comName: "ExamplePanel",
  //           },
  //         },
  //         {
  //           name: "TIFF",
  //           icon: "icon-lingcunwei",
  //           type: "button",
  //           enable: true,
  //           command: "OpenWidgetCommand", // 关闭一个组件
  //           lib: "WidgetPlugin",
  //           paramter: {
  //             comName: "PIETest",
  //             styles: "top:20px;right:20px;color:blue",
  //             comClass: "PIETest",
  //           },
  //         },
  //         {
  //           name: "IMG",
  //           icon: "icon-a-6guanbiwenjianjia",
  //           type: "button",
  //           enable: true,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "TILES",
  //           icon: "icon-a-6guanbiwenjianjia",
  //           type: "button",
  //           enable: true,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "3DTILES",
  //           icon: "icon-a-6guanbiwenjianjia",
  //           type: "button",
  //           enable: true,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "OSGB",
  //           icon: "icon-a-6guanbiwenjianjia",
  //           type: "button",
  //           enable: true,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "S3M",
  //           icon: "icon-a-6guanbiwenjianjia",
  //           type: "button",
  //           enable: true,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "S3M",
  //           icon: "icon-a-6guanbiwenjianjia",
  //           type: "button",
  //           enable: true,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //       ],
  //     },
  //     {
  //       name: "创建数据集",
  //       icon: "",
  //       type: "group",
  //       items: [
  //         {
  //           name: "点",
  //           icon: "icon-dian",
  //           type: "button",
  //           enable: true,
  //           checked: false,
  //           command: "DrawPointCommand",
  //           lib: "DrawPointPlugin",
  //           paramter: {
  //             styles: "",
  //             // comName: "PIEPointPanel",
  //           },
  //         },
  //         {
  //           name: "线",
  //           icon: "icon-xianduan",
  //           type: "button",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "面",
  //           icon: "icon-huizhimian",
  //           type: "button",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "CAD",
  //           icon: "icon-huizhimian",
  //           type: "button",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   name: "常规",
  //   icon: "",
  //   type: "page",
  //   groups: []
  // },
  // {
  //   name: "地图",
  //   icon: "",
  //   type: "page",
  //   groups: []
  // },
  {
    name: "编辑",
    icon: "",
    type: "page",
    groups: [
      {
        name: "编辑控制",
        icon: "",
        type: "group",
        items: [
          {
            name: "编辑控制",
            // icon: "icon-huizhimian",
            img: "edit-editControl.png",
            type: "dropList",
            // tip: "编辑控制",
            enable: true,
            checked: false,
            command: "EditControlCommand", // 执行一个功能
            lib: "DrawPlugin",
            paramter: {},
            children: [
              {
                name: "开始编辑",
                command: "DrawAddCommand",
                lib: "DrawPlugin",
                paramter: {
                  methods: "openDraw",
                },
                label: "编辑控制",
              },
              {
                name: "结束编辑",
                command: "DrawAddCommand",
                lib: "DrawPlugin",
                paramter: {
                  methods: "closeDraw",
                },
              },
            ],
          },
          {
            name: "编辑列表",
            // icon: "icon-huizhimian",
            type: "select_",
            tip: "编辑控制",
            enable: false,
            checked: false,
            command: "DrawAddCommand", // 执行一个功能
            lib: "DrawPlugin",
            paramter: {
              data: editableLayerList,
            },
          },
          // {
          //   name: "结束绘制",
          //   icon: "icon-huizhimian",
          //   type: "button",
          //   tip: "结束绘制",
          //   enable: true,
          //   checked: false,
          //   command: "DrawCloseCommand", // 执行一个功能
          //   lib: "DrawPlugin",
          //   paramter: {},
          // },
        ],
      },
      {
        name: "新建",
        icon: "",
        type: "group",
        items: [
          {
            name: "点",
            id: "edit_addPoint",
            img: "edit-addPoint.png",
            icon: "edit-addPoint", //class
            type: "button",
            enable: true,
            checked: false,
            command: "DrawAddCommand",
            buttonGroup: buttonGroupKeys.editAddGroup,
            lib: "DrawPlugin",
            paramter: {
              // styles: "",
              // comName: "",
              methods: "draw_point",
              mode: "changeMode",
            },
          },
          {
            name: "线",
            id: "edit_addLine",
            img: "edit-addLine.png",
            type: "dropList",
            enable: true,
            checked: false,
            command: "DrawAddCommand",
            buttonGroup: buttonGroupKeys.editAddGroup,
            lib: "DrawPlugin",
            paramter: {
              methods: "draw_line",
              mode: "changeMode",
            },
            children: [
              {
                name: "折线",
                command: "DrawAddCommand",
                lib: "DrawPlugin",
                paramter: {
                  methods: "draw_line",
                  mode: "changeMode",
                },
              },
              {
                name: "贝塞尔曲线",
                command: "DrawAddCommand",
                lib: "DrawPlugin",
                paramter: {
                  methods: "draw_bezier",
                  mode: "changeMode",
                },
              },
            ],
          },
          {
            name: "面",
            id: "edit_addPlolygon",
            img: "edit-addPloygon.png",
            type: "dropList",
            enable: true,
            checked: false,
            buttonGroup: buttonGroupKeys.editAddGroup,
            command: "DrawAddCommand",
            lib: "DrawPlugin",
            paramter: {
              // methods: "addPolygon",
            },
            children: [
              {
                name: "多边形",
                command: "DrawAddCommand",
                lib: "DrawPlugin",
                paramter: {
                  methods: "draw_polygon",
                  mode: "changeMode",
                },
              },
              {
                name: "矩形",
                command: "DrawAddCommand",
                lib: "DrawPlugin",
                paramter: {
                  methods: "draw_rect",
                  mode: "changeMode",
                },
              },
              {
                name: "圆",
                command: "DrawAddCommand",
                lib: "DrawPlugin",
                paramter: {
                  methods: "draw_circle",
                  mode: "changeMode",
                },
              },
            ],
          },
          {
            name: "文本",
            id: "edit_addText",
            img: "edit-addText.png",
            type: "button",
            enable: true,
            checked: false,
            buttonGroup: buttonGroupKeys.editAddGroup,
            command: "DrawAddCommand",
            lib: "DrawPlugin",
            paramter: {
              methods: "draw_text",
              mode: "changeMode",
              // methods: "addPolygon",
            },
          },
        ],
      },
      {
        name: "节点",
        icon: "",
        type: "group",
        items: [
          // {
          //   name: "编辑",
          //   // icon: "icon-bianjijiedian",
          //   icon: "",
          //   type: "button",
          //   enable: true,
          //   checked: false,
          //   buttonGroup: buttonGroupKeys.editAddGroup,
          //   command: "DrawAddCommand",
          //   lib: "DrawPlugin",
          //   paramter: {
          //     styles: "",
          //     comName: "",
          //     methods: "simple_select",
          //     mode: "changeMode",
          //   },
          // },
          {
            name: "添加",
            id: "edit_addNode",
            img: "edit-addNode.png",
            icon: "",
            type: "button",
            enable: false,
            checked: false,
            buttonGroup: buttonGroupKeys.editAddGroup,
            command: "DrawAddCommand",
            lib: "DrawPlugin",
            paramter: {
              methods: "direct_addNode",
              mode: "changeMode",
            },
          },
          {
            name: "移除",
            id: "edit_removeNode",
            img: "edit-removeNode.png",
            type: "button",
            enable: false,
            checked: false,
            buttonGroup: buttonGroupKeys.editAddGroup,
            command: "DrawAddCommand",
            lib: "DrawPlugin",
            paramter: {
              methods: "direct_deleteNode",
              mode: "changeMode",
            },
          },
        ],
      },
      {
        name: "编辑",
        icon: "",
        type: "group",
        items: [
          {
            name: "选择",
            id: "edit_select",
            img: "edit-select.png",
            noSelected: true,
            type: "button",
            enable: true,
            checked: false,
            buttonGroup: buttonGroupKeys.editAddGroup,
            command: "DrawAddCommand",
            lib: "DrawPlugin",
            paramter: {
              // styles: "",
              // comName: "",
              methods: "simple_select",
              mode: "changeMode",
            },
          },
          // {
          //   name: "剪切",
          //   icon: "icon-jianqie",
          //   type: "button",
          //   enable: true,
          //   checked: false,
          //   command: "DrawEditCommand",
          //   lib: "DrawPlugin",
          //   paramter: {
          //     methods: "delete"
          //   }
          // },
          {
            name: "复制",
            id: "edit_copy",
            img: "edit-copy.png",
            noSelected: true,
            icon: "",
            type: "button",
            enable: false,
            buttonGroup: buttonGroupKeys.editAddGroup,
            command: "DrawAddCommand",
            lib: "DrawPlugin",
            paramter: {
              methods: "copy",
            },
          },
          {
            name: "粘贴",
            id: "edit_paste",
            img: "edit-paste.png",
            noSelected: true,
            icon: "",
            type: "button",
            enable: false,
            buttonGroup: buttonGroupKeys.editAddGroup,
            command: "DrawAddCommand",
            lib: "DrawPlugin",
            paramter: {
              methods: "paste",
            },
          },
          {
            name: "删除",
            id: "edit_delete",
            img: "edit-delete.png",
            noSelected: true,
            icon: "",
            type: "button",
            enable: true,
            buttonGroup: buttonGroupKeys.editAddGroup,
            command: "DrawAddCommand",
            lib: "DrawPlugin",
            paramter: {
              methods: "delete",
            },
          },
          {
            name: "撤销",
            id: "edit_undo",
            img: "edit-undo.png",
            noSelected: true,
            icon: "",
            type: "button",
            enable: true,
            buttonGroup: buttonGroupKeys.editAddGroup,
            command: "DrawAddCommand",
            lib: "DrawPlugin",
            paramter: {
              methods: "undo",
            },
          },
          {
            name: "重做",
            id: "edit_redo",
            img: "edit-redo.png",
            noSelected: true,
            icon: "",
            type: "button",
            enable: true,
            buttonGroup: buttonGroupKeys.editAddGroup,
            command: "DrawAddCommand",
            lib: "DrawPlugin",
            paramter: {
              methods: "redo",
            },
          },
        ],
      },
      {
        name: "要素",
        icon: "",
        type: "group",
        items: [
          {
            name: "裁剪",
            id: "edit_cut",
            img: "edit-crop.png",
            icon: "",
            type: "button",
            enable: true,
            checked: false,
            command: "",
            lib: "",
            paramter: {
              styles: "",
              comName: "",
            },
          },
          {
            name: "合并",
            id: "edit_combine",
            img: "edit-combine.png",
            icon: "",
            type: "button",
            enable: true,
            checked: false,
            command: "",
            lib: "",
            paramter: {},
          },
          {
            name: "拆分",
            id: "edit_split",
            img: "edit-split.png",
            icon: "",
            type: "button",
            enable: true,
            checked: false,
            command: "",
            lib: "",
            paramter: {},
          },
          {
            name: "求交",
            id: "edit_intersect",
            img: "edit-intersect.png",
            icon: "",
            type: "button",
            enable: true,
            checked: false,
            command: "",
            lib: "",
            paramter: {},
          },
        ],
      },
      {
        name: "捕捉",
        icon: "",
        type: "group",
        items: [
          {
            name: "点",
            id: "edit_catchPoint",
            img: "edit-catchPoint.png",
            label: "点",
            // icon: "icon-dian",
            icon: "",
            type: "button",
            enable: true,
            checked: false,
            command: "DrawAddCommand",
            lib: "DrawPlugin",
            paramter: {
              methods: "catchPoint",
            },
          },
          {
            name: "线",
            id: "edit_catchLine",
            img: "edit-catchLine.png",
            icon: "",
            type: "button",
            enable: true,
            checked: false,
            command: "DrawAddCommand",
            lib: "DrawPlugin",
            paramter: {
              methods: "catchLine",
            },
          },
          {
            name: "折点",
            id: "edit_catchKneePoint",
            img: "edit-catchKneePoint.png",
            icon: "",
            type: "button",
            enable: true,
            checked: false,
            command: "DrawAddCommand",
            lib: "DrawPlugin",
            paramter: {
              methods: "catchKneePoint",
            },
          },
        ],
      },
      {
        name: "",
        icon: "",
        type: "group",
        items: [
          {
            name: "属性编辑",
            img: "edit-openSet.png",
            icon: "",
            type: "button",
            enable: true,
            checked: false,
            command: "",
            lib: "",
            paramter: {
              styles: "",
              comName: "",
            },
          },
        ],
      },
      {
        name: "模型",
        icon: "",
        type: "group",
        items: [
          {
            name: "平移",
            id: "edit_translate",
            img: "edit-translate.png",
            type: "button",
            enable: true,
            checked: false,
            buttonGroup: buttonGroupKeys.editAddGroup,
            command: "DrawAddCommand",
            lib: "DrawPlugin",
            paramter: {
              methods: "editTranslate",
              toolType: "EditPan",
            },
          },
          {
            name: "调整高度",
            id: "edit_height_adjustment",
            img: "edit-height-adjustment.png",
            icon: "",
            type: "button",
            enable: false,
            buttonGroup: buttonGroupKeys.editAddGroup,
            command: "DrawAddCommand",
            lib: "DrawPlugin",
            paramter: {
              methods: "editHeightAdjustment",
              toolType: "EditHeight",
            },
          },
          {
            name: "旋转",
            id: "edit_rotate",
            img: "edit-rotate.png",
            icon: "",
            type: "button",
            enable: false,
            buttonGroup: buttonGroupKeys.editAddGroup,
            command: "DrawAddCommand",
            lib: "DrawPlugin",
            paramter: {
              methods: "editRotate",
              toolType: "EditRotate",
            },
          },
          {
            name: "缩放",
            id: "edit_zoom",
            img: "edit-zoom.png",
            icon: "",
            type: "button",
            enable: true,
            buttonGroup: buttonGroupKeys.editAddGroup,
            command: "DrawAddCommand",
            lib: "DrawPlugin",
            paramter: {
              methods: "editZoom",
              toolType: "EditScale",
            },
          },
        ],
      },
    ],
  },
  // {
  //   name: "处理",
  //   icon: "",
  //   type: "page",
  //   groups: []
  // },
  {
    name: "分析",
    icon: "",
    type: "page",
    groups: [
      {
        name: "地表量算",
        icon: "",
        type: "group",
        items: [
          {
            name: "地表距离",
            img: "analysis-distance.png",
            type: "button",
            buttonGroup: buttonGroupKeys.measureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEMeasurePanel",
              _props: {
                measureType: "Distance",
                measureName: "地表距离",
              },
            },
          },
          {
            name: "地表角度",
            img: "analysis-angle.png",
            type: "button",
            buttonGroup: buttonGroupKeys.measureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEMeasurePanel",
              _props: {
                measureType: "Angle",
                measureName: "地表角度",
              },
            },
          },
          {
            name: "地表面积",
            img: "analysis-area.png",
            type: "button",
            buttonGroup: buttonGroupKeys.measureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEMeasurePanel",
              _props: {
                measureType: "Area",
                measureName: "地表面积",
              },
            },
          },
        ],
      },
      {
        name: "空间量算",
        icon: "",
        type: "group",
        items: [
          {
            name: "空间距离",
            img: "analysis-distance3D.png",
            type: "button",
            buttonGroup: buttonGroupKeys.measureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand", // 打开一个组件
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEMeasurePanel",
              _props: {
                measureType: "Distance3D",
                measureName: "空间距离",
              },
            },
          },
          {
            name: "空间角度",
            img: "analysis-angle3D.png",
            type: "button",
            buttonGroup: buttonGroupKeys.measureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand", // 打开一个组件
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEMeasurePanel",
              _props: {
                measureType: "Angle3D",
                measureName: "空间角度",
              },
            },
          },
          {
            name: "空间面积",
            img: "analysis-area3D.png",
            type: "button",
            buttonGroup: buttonGroupKeys.measureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEMeasurePanel",
              _props: {
                measureType: "Area3D",
                measureName: "空间面积",
              },
            },
          },
          {
            name: "高程",
            img: "analysis-height3D.png",
            type: "button",
            buttonGroup: buttonGroupKeys.measureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEMeasurePanel",
              _props: {
                measureType: "Height3D",
                measureName: "高程",
              },
            },
          },
          {
            name: "体积量算",
            img: "analysis-volumn.png",
            type: "button",
            buttonGroup: buttonGroupKeys.measureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEVolumeMeasurePanel",
              _props: {
                measureType: "Volume",
                measureName: "体积",
                measureUnit: "立方米",
              },
            },
          },
        ],
      },
      {
        name: "通视分析",
        icon: "",
        type: "group",
        items: [
          {
            name: "点线通视",
            img: "analysis-pntline.png",
            type: "dropList",
            buttonGroup: buttonGroupKeys.measureGroup,
            enable: true,
            checked: false,
            command: "",
            lib: "",
            children: [
              {
                img: "analysis-pntline.png",
                name: "地形点线通视",
                command: "OpenWidgetCommand",
                lib: "WidgetPlugin",
                paramter: {
                  styles: "padding-right: 10px;",
                  comName: "PIEAnalyseVisiblePanel",
                  _props: {
                    analyseVisibleType: "AnalyseVisibleLine",
                    analyseVisibleName: "地形点线通视",
                  },
                },
              },
              {
                img: "analysis-pntline.png",
                name: "模型点线通视",
                command: "OpenWidgetCommand",
                lib: "WidgetPlugin",
                paramter: {
                  styles: "padding-right: 10px;",
                  comName: "PIEAnalyseVisiblePanel",
                  _props: {
                    analyseVisibleType: "Analyse3DVisibleLine",
                    analyseVisibleName: "模型点线通视",
                  },
                },
              },
            ],
          },
          {
            name: "点面通视",
            img: "analysis-pntarea.png",
            type: "dropList",
            buttonGroup: buttonGroupKeys.measureGroup,
            enable: true,
            checked: false,
            command: "",
            lib: "",
            paramter: {},
            children: [
              {
                name: "地形点面通视",
                img: "analysis-pntarea.png",
                command: "OpenWidgetCommand",
                lib: "WidgetPlugin",
                paramter: {
                  styles: "padding-right: 10px;",
                  comName: "PIEAnalyseVisiblePanel",
                  _props: {
                    analyseVisibleType: "AnalyseVisibleRegion",
                    analyseVisibleName: "地形点面通视",
                  },
                },
              },
              {
                name: "模型点面通视",
                img: "analysis-pntarea.png",
                command: "OpenWidgetCommand",
                lib: "WidgetPlugin",
                paramter: {
                  styles: "padding-right: 10px;",
                  comName: "PIEAnalyseVisiblePanel",
                  _props: {
                    analyseVisibleType: "Analyse3DVisibleRegion",
                    analyseVisibleName: "模型点面通视",
                  },
                },
              },
            ],
          },
        ],
      },
      {
        name: "地形分析",
        icon: "",
        type: "group",
        items: [
          {
            name: "坡度坡向",
            img: "analysis-slope.png",
            type: "button",
            buttonGroup: buttonGroupKeys.measureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIESlopeAnalysisPanel",
              _props: {
                slopeDgree: "坡度",
                slopeAspect: "坡向",
              },
            },
          },
          {
            name: "淹没",
            img: "analysis-flood.png",
            type: "button",
            buttonGroup: buttonGroupKeys.measureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEFloodAnalysisPanel",
              _props: {
                slopeDgree: "",
                slopeAspect: "",
              },
            },
          },
          {
            name: "土方",
            // img: "analysisEarthwork",
            type: "button",
            enable: false,
            checked: false,
            // command: "EmptyCommand",
            // lib: "AnalysisPlugin",
            paramter: {},
          },
        ],
      },
      {
        name: "模型分析",
        icon: "",
        img: "",
        type: "group",
        items: [
          {
            name: "日照",
            img: "analysis-sunshine.png",
            type: "button",
            buttonGroup: buttonGroupKeys.measureGroup,
            enable: true,
            checked: false,
            command: "ShadowRateCommand",
            lib: "AnalysisPlugin",
            paramter: {},
          },
          {
            name: "天际线",
            icon: "",
            img: "analysis-skyline.png",
            type: "button",
            buttonGroup: buttonGroupKeys.measureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEAnalyseSkyLinePanel",
              _props: {},
            },
          },
          {
            name: "剖面",
            icon: "",
            img: "analysis-cutaway.png",
            type: "button",
            buttonGroup: buttonGroupKeys.measureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEAnalyseCutawayPanel",
              _props: {},
            },
          },
        ],
      },
      {
        name: "缓冲区分析",
        icon: "",
        type: "group",
        items: [
          {
            name: "缓冲区分析",
            img: "analysis-buffer.png",
            type: "button",
            buttonGroup: buttonGroupKeys.measureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEBufferPanel",
              _props: {},
            },
          },
        ],
      },
      {
        name: "拓扑分析",
        icon: "",
        type: "group",
        items: [
          {
            name: "拓扑分析",
            img: "analysis-buffer.png",
            type: "button",
            buttonGroup: buttonGroupKeys.measureGroup,
            enable: false,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIETopoPanel",
              _props: {},
            },
          },
        ],
      },
    ],
  },
  {
    name: "在线分析",
    icon: "",
    type: "page",
    groups: [
      {
        name: "地表量算",
        icon: "",
        type: "group",
        items: [
          {
            name: "地表距离",
            img: "analysis-distance.png",
            type: "button",
            buttonGroup: buttonGroupKeys.onlineMeasureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEMeasureOnlinePanel",
              _props: {
                measureType: 1,
                measureName: "地表距离",
              },
            },
          },
          {
            name: "地表角度",
            img: "analysis-angle.png",
            type: "button",
            buttonGroup: buttonGroupKeys.onlineMeasureGroup,
            enable: false,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEMeasureOnlinePanel",
              _props: {
                measureType: 2,
                measureName: "地表角度",
              },
            },
          },
          {
            name: "地表面积",
            img: "analysis-area.png",
            type: "button",
            buttonGroup: buttonGroupKeys.onlineMeasureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEMeasureOnlinePanel",
              _props: {
                measureType: 3,
                measureName: "地表面积",
              },
            },
          },
        ],
      },
      {
        name: "空间量算",
        icon: "",
        type: "group",
        items: [
          {
            name: "空间距离",
            img: "analysis-distance3D.png",
            type: "button",
            buttonGroup: buttonGroupKeys.onlineMeasureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand", // 打开一个组件
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEMeasureOnlinePanel",
              _props: {
                measureType: 4,
                measureName: "空间距离",
              },
            },
          },
          {
            name: "空间角度",
            img: "analysis-angle3D.png",
            type: "button",
            buttonGroup: buttonGroupKeys.onlineMeasureGroup,
            enable: false,
            checked: false,
            command: "OpenWidgetCommand", // 打开一个组件
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEMeasureOnlinePanel",
              _props: {
                measureType: 5,
                measureName: "空间角度",
              },
            },
          },
          {
            name: "空间面积",
            img: "analysis-area3D.png",
            type: "button",
            buttonGroup: buttonGroupKeys.onlineMeasureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEMeasureOnlinePanel",
              _props: {
                measureType: 6,
                measureName: "空间面积",
              },
            },
          },
          {
            name: "高程",
            img: "analysis-height3D.png",
            type: "button",
            buttonGroup: buttonGroupKeys.onlineMeasureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEMeasureOnlinePanel",
              _props: {
                measureType: 7,
                measureName: "高程",
              },
            },
          },
          {
            name: "体积量算",
            img: "analysis-volumn.png",
            type: "button",
            buttonGroup: buttonGroupKeys.onlineMeasureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEVolumeMeasureOnlinePanel",
              _props: {
                measureType: 8,
                measureName: "体积",
                measureUnit: "立方米",
              },
            },
          },
        ],
      },
      {
        name: "通视分析",
        icon: "",
        type: "group",
        items: [
          {
            name: "地形点线通视",
            img: "analysis-pntline.png",
            type: "button",
            buttonGroup: buttonGroupKeys.onlineMeasureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEAnalyseVisibleOnlinePanel",
              _props: {
                analyseVisibleType: "AnalyseVisibleLine",
                analyseVisibleName: "地形点线通视",
              },
            },
          },
          {
            name: "地形点面通视",
            img: "analysis-pntarea.png",
            type: "button",
            buttonGroup: buttonGroupKeys.onlineMeasureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEAnalyseVisibleOnlinePanel",
              _props: {
                analyseVisibleType: "AnalyseVisibleRegion",
                analyseVisibleName: "地形点面通视",
              },
            },
          },
        ],
      },
      {
        name: "地形分析",
        icon: "",
        type: "group",
        items: [
          {
            name: "坡度坡向",
            img: "analysis-slope.png",
            type: "button",
            buttonGroup: buttonGroupKeys.onlineMeasureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIESlopeAnalysisOnlinePanel",
              _props: {
                slopeDgree: "坡度",
                slopeAspect: "坡向",
              },
            },
          },
          {
            name: "淹没",
            img: "analysis-flood.png",
            type: "button",
            buttonGroup: buttonGroupKeys.onlineMeasureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEFloodAnalysisOnlinePanel",
              _props: {
                slopeDgree: "",
                slopeAspect: "",
              },
            },
          },
          {
            name: "土方",
            img: "analysis-earthwork.png",
            type: "button",
            buttonGroup: buttonGroupKeys.onlineMeasureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEAnalyseExcavationOnlinePanel",
              _props: {},
            },
          },
          {
            name: "剖面",
            img: "analysis-cutaway.png",
            type: "button",
            buttonGroup: buttonGroupKeys.onlineMeasureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEAnalyseCutawayOnlinePanel",
              _props: {},
            },
          },
        ],
      },
      //   {
      //     name: "模型分析",
      //     icon: "",
      //     img: "",
      //     type: "group",
      //     items: [
      //       {
      //         name: "日照",
      //         // img: "analysisSunshine",
      //         type: "button",
      //         buttonGroup: buttonGroupKeys.onlineMeasureGroup,
      //         enable: false,
      //         checked: false,
      //         command: "ShadowRateCommand",
      //         lib: "AnalysisPlugin",
      //         paramter: {},
      //       },
      //       {
      //         name: "天际线",
      //         icon: "",
      //         // img: "analysisSkyline",
      //         type: "button",
      //         enable: false,
      //         checked: false,
      //         // command: "EmptyCommand",
      //         // lib: "AnalysisPlugin",
      //         paramter: {},
      //       },
      //       {
      //         name: "剖面",
      //         // img: "analysisCutaway",
      //         type: "button",
      //         enable: false,
      //         checked: false,
      //         // command: "EmptyCommand",
      //         // lib: "AnalysisPlugin",
      //         paramter: {},
      //       },
      //     ],
      //   },
      {
        name: "缓冲区分析",
        icon: "",
        type: "group",
        items: [
          {
            name: "缓冲区分析",
            img: "analysis-buffer.png",
            type: "button",
            buttonGroup: buttonGroupKeys.onlineMeasureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEBufferOnlinePanel",
              _props: {},
            },
          },
        ],
      },
      {
        name: "拓扑分析",
        icon: "",
        type: "group",
        items: [
          {
            name: "拓扑分析",
            img: "analysis-buffer.png",
            type: "button",
            buttonGroup: buttonGroupKeys.onlineMeasureGroup,
            enable: true,
            checked: false,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIETopoOnlinePanel",
              _props: {},
            },
          },
        ],
      },
    ],
  },
  {
    name: "浏览",
    icon: "",
    type: "page",
    groups: [
      // {
      //   name: "模式",
      //   icon: "",
      //   type: "group",
      //   items: [
      //     {
      //       name: "平面模式",
      //       icon: "",
      //       type: "button",
      //       tip: "平面模式",
      //       enable: true,
      //       checked: false,
      //       command: "",
      //       lib: "",
      //       paramter: {},
      //     },
      //     {
      //       name: "球面模式",
      //       // icon: "",
      //       img: "scene-spherical.png",
      //       type: "button",
      //       tip: "球面模式",
      //       enable: true,
      //       checked: false,
      //       command: "",
      //       lib: "",
      //       paramter: {},
      //     },
      //   ],
      // },
      // {
      //   name: "背景色",
      //   icon: "",
      //   type: "group",
      //   items: [
      //     {
      //       name: "窗口底色",
      //       icon: "",
      //       type: "button",
      //       tip: "窗口底色",
      //       enable: true,
      //       checked: false,
      //       command: "",
      //       lib: "",
      //       paramter: {},
      //     },
      //     {
      //       name: "球面底色",
      //       icon: "",
      //       type: "button",
      //       tip: "球面底色",
      //       enable: true,
      //       checked: false,
      //       command: "",
      //       lib: "",
      //       paramter: {},
      //     },
      //   ],
      // },
      // {
      //   name: "场景模式",
      //   icon: "",
      //   type: "group",
      //   items: [
      //     {
      //       name: "经纬网",
      //       // icon: "",
      //       img: "scene-graticule.png",
      //       type: "button",
      //       tip: "经纬网",
      //       enable: true,
      //       checked: false,
      //       command: "",
      //       lib: "",
      //       paramter: {},
      //     },
      //     {
      //       name: "太阳",
      //       // icon: "",
      //       img: "scene-sun.png",
      //       type: "button",
      //       tip: "太阳",
      //       enable: true,
      //       checked: false,
      //       command: "",
      //       lib: "",
      //       paramter: {},
      //     },
      //     {
      //       name: "日照",
      //       // icon: "",
      //       img: "scene-sunshine.png",
      //       type: "button",
      //       tip: "日照",
      //       enable: true,
      //       checked: false,
      //       command: "",
      //       lib: "",
      //       paramter: {},
      //     },
      //     {
      //       name: "大气层",
      //       // icon: "",
      //       img: "scene-atmosphere.png",
      //       type: "button",
      //       tip: "大气层",
      //       enable: true,
      //       checked: false,
      //       command: "",
      //       lib: "",
      //       paramter: {},
      //     },
      //     {
      //       name: "海洋",
      //       // icon: "",
      //       img: "scene-ocean.png",
      //       type: "button",
      //       tip: "海洋",
      //       enable: true,
      //       checked: false,
      //       command: "",
      //       lib: "",
      //       paramter: {},
      //     },
      //   ],
      // },

      {
        name: "地图工具",
        icon: "",
        type: "group",
        items: [
          {
            name: "鹰眼图",
            icon: "icon-yingyantu1",
            type: "button",
            tip: "鹰眼图",
            enable: true,
            checked: false,
            command: "EagleEyeControlCommand",
            lib: "EagleEyeControlPlugin",
            paramter: {},
          },
          {
            name: "键盘漫游",
            // icon: "",
            img: "scene-keyboard.png",
            type: "button",
            tip: "键盘漫游",
            enable: true,
            checked: false,
            command: "RoamCommand",
            lib: "MapToolsPlugin",
            paramter: {},
          },
          {
            name: "放大",
            // icon: "",
            img: "scene-magnify.png",
            type: "button",
            tip: "放大",
            enable: true,
            checked: false,
            command: "ZoomOutCommand",
            lib: "MapToolsPlugin",
            paramter: {},
          },
          {
            name: "缩小",
            // icon: "",
            img: "scene-reduction.png",
            type: "button",
            tip: "缩小",
            enable: true,
            checked: false,
            command: "ZoomInCommand",
            lib: "MapToolsPlugin",
            paramter: {},
          },
          {
            name: "区域放大",
            // icon: "",
            img: "scene-area-in.png",
            type: "button",
            tip: "区域放大",
            enable: true,
            checked: false,
            buttonGroup: buttonGroupKeys.mapToolGroup,
            command: "AreaZoomInCommand",
            lib: "MapToolsPlugin",
            paramter: {},
          },
          {
            name: "区域缩小",
            // icon: "",
            img: "scene-area-reduction.png",
            type: "button",
            tip: "区域缩小",
            enable: true,
            checked: false,
            buttonGroup: buttonGroupKeys.mapToolGroup,
            command: "AreaReductionCommand",
            lib: "MapToolsPlugin",
            paramter: {},
          },
          {
            name: "全图显示",
            // icon: "",
            img: "scene-full-image.png",
            type: "button",
            tip: "全图显示",
            enable: true,
            checked: false,
            command: "FullExtentCommand",
            lib: "MapToolsPlugin",
            paramter: {},
          },
          {
            name: "区域锁定",
            // icon: "",
            img: "scene-lock.png",
            type: "button",
            tip: "区域锁定",
            enable: true,
            checked: false,
            command: "RegionLockCommand",
            lib: "MapToolsPlugin",
            paramter: {},
          },
          {
            name: "定位",
            // icon: "",
            img: "scene-positioning.png",
            type: "button",
            tip: "定位",
            enable: true,
            checked: false,
            buttonGroup: buttonGroupKeys.measureGroup,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIELocationPanel",
            },
          },
          // {
          //   name: "单体选择",
          //   // icon: "",
          //   img: "scene-select.png",
          //   type: "button",
          //   tip: "单体选择",
          //   enable: true,
          //   checked: false,
          //   command: "",
          //   lib: "",
          //   paramter: {},
          // },
          {
            name: "刷新",
            // icon: "",
            img: "scene-refresh.png",
            type: "button",
            tip: "刷新",
            enable: true,
            checked: false,
            command: "RefreshCommand",
            lib: "MapToolsPlugin",
            paramter: {},
          },
          {
            name: "卷帘",
            // icon: "",
            img: "scene-roller.png",
            type: "button",
            tip: "卷帘",
            enable: true,
            checked: false,
            buttonGroup: buttonGroupKeys.measureGroup,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIERollerBlinder",
            },
          },
          {
            name: "三维环绕",
            // icon: "",
            img: "scene-wrapping.png",
            type: "button",
            tip: "三维环绕",
            enable: true,
            checked: false,
            command: "RotatingCommand",
            lib: "RotatingPlugin",
            paramter: {},
          },
          {
            name: "路径漫游",
            icon: "icon-xunimanyou",
            type: "button",
            tip: "路径漫游",
            enable: true,
            checked: true,
            buttonGroup: buttonGroupKeys.measureGroup,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEPathWonderPanel",
              _props: { measureType: 7, measureName: "高程" },
            },
          },
          {
            name: "图层轮播",
            icon: "icon-lunbotu",
            type: "button",
            tip: "图层轮播",
            enable: true,
            checked: true,
            buttonGroup: buttonGroupKeys.measureGroup,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIECarousel",
              _props: {},
            },
          },
          // {
          //       name: "雷达",
          //       img: "",
          //       type: "button",
          //       tip: "雷达",
          //       enable: true,
          //       checked: false,
          //       command: "RadarAddCommand",
          //       lib: "RadarPlugin",
          //       paramter: {},
          //   },

          // {
          //     name: "欢迎",
          //     // icon: "",
          //     img: "scene-roller.png",
          //     type: "button",
          //     tip: "欢迎",
          //     enable: true,
          //     checked: false,
          //     buttonGroup: buttonGroupKeys.measureGroup,
          //     command: "OpenWidgetCommand",
          //     lib: "WidgetPlugin",
          //     paramter: {
          //         comName: "WelcomePanel",
          //     },
          //  },
          // {
          //       name: "视角切换",
          //       icon: "",
          //       type: "button",
          //       tip: "视角切换",
          //       enable: true,
          //       checked: false,
          //       buttonGroup: buttonGroupKeys.measureGroup,
          //       command: "OpenWidgetCommand",
          //       lib: "WidgetPlugin",
          //       paramter: {
          //           comName: "PIEViewSwitch",
          //       },
          //   },
          // {
          //       name: "二三维联动",
          //       icon: "",
          //       type: "button",
          //       tip: "二三维联动",
          //       enable: true,
          //       checked: false,
          //       command: "EarthMapboxAssociatingCommand",
          //       lib: "EarthMapboxAssociatingPlugin",
          //       paramter: {},
          //   },
        ],
      },
      {
        name: "导出工具",
        icon: "",
        type: "group",
        items: [
          {
            name: "导出",
            icon: "icon-daochu",
            type: "button",
            tip: "导出",
            enable: true,
            checked: true,
            buttonGroup: buttonGroupKeys.mapToolGroup,
            command: "OpenWidgetCommand",
            lib: "WidgetPlugin",
            paramter: {
              comName: "PIEExportImg",
              _props: {},
            },
          },
        ],
      },
    ],
  },
  // {
  //   name: "雷达",
  //   icon: "",
  //   type: "page",
  //   groups: [
  //     {
  //       name: "常规",
  //       icon: "",
  //       type: "group",
  //       items: [
  //         {
  //           name: "添加",
  //           img: "analysis-radar.png",
  //           type: "button",
  //           buttonGroup: buttonGroupKeys.measureGroup,
  //           enable: true,
  //           checked: false,
  //           command: "OpenWidgetCommand",
  //           lib: "WidgetPlugin",
  //           paramter: {
  //             comName: "PIERadarPanel",
  //           },
  //         },
  //         {
  //           name: "配置",
  //           img: "analysis-radar.png",
  //           type: "button",
  //           buttonGroup: buttonGroupKeys.measureGroup,
  //           enable: false,
  //           checked: false,
  //           command: "OpenWidgetCommand",
  //           lib: "WidgetPlugin",
  //           paramter: {
  //             comName: "",
  //           },
  //         },
  //       ],
  //     },
  //     {
  //       name: "雷达",
  //       icon: "",
  //       type: "group",
  //       items: [
  //         {
  //           name: "无干扰",
  //           img: "analysis-radar.png",
  //           type: "button",
  //           buttonGroup: buttonGroupKeys.measureGroup,
  //           enable: false,
  //           checked: false,
  //           command: "OpenWidgetCommand",
  //           lib: "WidgetPlugin",
  //           paramter: {
  //             comName: "",
  //           },
  //         },
  //         {
  //           name: "组网",
  //           img: "analysis-radar.png",
  //           type: "button",
  //           buttonGroup: buttonGroupKeys.measureGroup,
  //           enable: false,
  //           checked: false,
  //           command: "OpenWidgetCommand",
  //           lib: "WidgetPlugin",
  //           paramter: {
  //             comName: "",
  //           },
  //         },
  //         {
  //           name: "动画",
  //           img: "analysis-flood.png",
  //           type: "button",
  //           buttonGroup: buttonGroupKeys.measureGroup,
  //           enable: false,
  //           checked: false,
  //           command: "OpenWidgetCommand",
  //           lib: "WidgetPlugin",
  //           paramter: {
  //             comName: "",
  //           },
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //     name: "标绘",
  //     icon: "",
  //     type: "page",
  //     groups: [
  //         {
  //             name: "军标标绘",
  //             icon: "",
  //             type: "group",
  //             items: [
  //                 {
  //                     name: "军标面板",
  //                     icon: "",
  //                     type: "button",
  //                     buttonGroup: buttonGroupKeys.plottingGroup,
  //                     enable: true,
  //                     checked: false,
  //                     command: "AreaMeasureCommand",
  //                     lib: "AnalysisPlugin",
  //                     paramter: {},
  //                 },
  //                 {
  //                     name: "标绘属性",
  //                     icon: "",
  //                     type: "button",
  //                     buttonGroup: buttonGroupKeys.plottingGroup,
  //                     enable: true,
  //                     checked: false,
  //                     command: "AreaMeasureCommand",
  //                     lib: "AnalysisPlugin",
  //                     paramter: {},
  //                 },
  //             ],
  //         },
  //         {
  //             name: "气象标绘",
  //             icon: "",
  //             type: "group",
  //             items: [
  //                 {
  //                     name: "气象面板",
  //                     icon: "",
  //                     type: "button",
  //                     buttonGroup: buttonGroupKeys.plottingGroup,
  //                     enable: true,
  //                     checked: false,
  //                     command: "AreaMeasureCommand",
  //                     lib: "AnalysisPlugin",
  //                     paramter: {},
  //                 },
  //             ],
  //         },
  //     ],
  // },
  // {
  //   name: "标绘",
  //   icon: "",
  //   type: "page",
  //   groups: [
  //     {
  //       name: "军标标绘",
  //       icon: "",
  //       type: "group",
  //       items: [
  //         {
  //           name: "军标面板",
  //           icon: "",
  //           type: "button",
  //           enable: true,
  //           checked: false,
  //           command: "AreaMeasureCommand",
  //           lib: "AnalysisPlugin",
  //           paramter: {},
  //         },
  //         {
  //           name: "标绘属性",
  //           icon: "",
  //           type: "button",
  //           enable: true,
  //           checked: false,
  //           command: "AreaMeasureCommand",
  //           lib: "AnalysisPlugin",
  //           paramter: {},
  //         },
  //       ],
  //     },
  //     {
  //       name: "气象标绘",
  //       icon: "",
  //       type: "group",
  //       items: [
  //         {
  //           name: "气象面板",
  //           icon: "",
  //           type: "button",
  //           enable: true,
  //           checked: false,
  //           command: "AreaMeasureCommand",
  //           lib: "AnalysisPlugin",
  //           paramter: {},
  //         },
  //         {
  //           name: "标绘属性",
  //           icon: "",
  //           type: "button",
  //           enable: true,
  //           checked: false,
  //           command: "AreaMeasureCommand",
  //           lib: "AnalysisPlugin",
  //           paramter: {},
  //         },
  //       ],
  //     },
  //     {
  //       name: "模型标绘",
  //       icon: "",
  //       type: "group",
  //       items: [
  //         {
  //           name: "气象面板",
  //           icon: "",
  //           type: "button",
  //           tip: "气象面板",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //       ],
  //     },
  //     {
  //       name: "3D模型标绘",
  //       icon: "",
  //       type: "group",
  //       items: [
  //         {
  //           name: "添加模型",
  //           icon: "",
  //           type: "button",
  //           tip: "添加模型",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "平移",
  //           icon: "",
  //           type: "button",
  //           tip: "平移",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "升降",
  //           icon: "",
  //           type: "button",
  //           tip: "升降",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "旋转",
  //           icon: "",
  //           type: "button",
  //           tip: "旋转",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "缩放",
  //           icon: "",
  //           type: "button",
  //           tip: "缩放",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   name: "工具",
  //   icon: "",
  //   type: "page",
  //   groups: [
  //     {
  //       name: "投影工具",
  //       icon: "",
  //       type: "group",
  //       items: [
  //         {
  //           name: "投影定义",
  //           icon: "",
  //           type: "button",
  //           tip: "投影定义",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "影像投影转换",
  //           icon: "",
  //           type: "button",
  //           tip: "影像投影转换",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "矢量投影转换",
  //           icon: "",
  //           type: "button",
  //           tip: "矢量投影转换",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //       ],
  //     },
  //     {
  //       name: "切图工具",
  //       icon: "",
  //       type: "group",
  //       items: [
  //         {
  //           name: "瓦片配置",
  //           icon: "",
  //           type: "button",
  //           tip: "瓦片配置",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "栅格瓦片",
  //           icon: "",
  //           type: "button",
  //           tip: "栅格瓦片",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "矢量瓦片",
  //           icon: "",
  //           type: "button",
  //           tip: "矢量瓦片",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "地形瓦片",
  //           icon: "",
  //           type: "button",
  //           tip: "地形瓦片",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //       ],
  //     },
  //     {
  //       name: "数据处理",
  //       icon: "",
  //       type: "group",
  //       items: [
  //         {
  //           name: "生成OSGB配置文件",
  //           icon: "",
  //           type: "button",
  //           tip: "生成OSGB配置文件",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "数据转换",
  //           icon: "",
  //           type: "button",
  //           tip: "数据转换",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "根节点合并",
  //           icon: "",
  //           type: "button",
  //           tip: "根节点合并",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "实景三维转换工具",
  //           icon: "",
  //           type: "button",
  //           tip: "实景三维转换工具",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //       ],
  //     },
  //     {
  //       name: "影像处理",
  //       icon: "",
  //       type: "group",
  //       items: [
  //         {
  //           name: "金字塔",
  //           icon: "",
  //           type: "button",
  //           tip: "金字塔",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "裁剪",
  //           icon: "",
  //           type: "button",
  //           tip: "裁剪",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "掩膜",
  //           icon: "",
  //           type: "button",
  //           tip: "掩膜",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //       ],
  //     },
  //     {
  //       name: "矢量处理",
  //       icon: "",
  //       type: "group",
  //       items: [
  //         {
  //           name: "重采样",
  //           icon: "",
  //           type: "button",
  //           tip: "重采样",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "军图转换",
  //           icon: "",
  //           type: "button",
  //           tip: "军图转换",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "OSM数据转换",
  //           icon: "",
  //           type: "button",
  //           tip: "OSM数据转换",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //       ],
  //     },
  //     {
  //       name: "快照",
  //       icon: "",
  //       type: "group",
  //       items: [
  //         {
  //           name: "多视角拍摄",
  //           icon: "",
  //           type: "button",
  //           tip: "多视角拍摄",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "快照停止",
  //           icon: "",
  //           type: "button",
  //           tip: "快照停止",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "打开快照位置",
  //           icon: "",
  //           type: "button",
  //           tip: "打开快照位置",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   name: "视图",
  //   icon: "",
  //   type: "page",
  //   groups: [
  //     {
  //       name: "窗口排列",
  //       icon: "",
  //       type: "group",
  //       items: [
  //         {
  //           name: "标签排列",
  //           icon: "",
  //           type: "button",
  //           tip: "标签排列",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "水平排列",
  //           icon: "",
  //           type: "button",
  //           tip: "水平排列",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "垂直排列",
  //           icon: "",
  //           type: "button",
  //           tip: "垂直排列",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //       ],
  //     },
  //     {
  //       name: "视图",
  //       icon: "",
  //       type: "group",
  //       items: [
  //         {
  //           name: "浮动",
  //           icon: "",
  //           type: "button",
  //           tip: "浮动",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "全屏",
  //           icon: "",
  //           type: "button",
  //           tip: "全屏",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "切换窗口",
  //           icon: "",
  //           type: "button",
  //           tip: "切换窗口",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //         {
  //           name: "视图重置",
  //           icon: "",
  //           type: "button",
  //           tip: "视图重置",
  //           enable: true,
  //           checked: false,
  //           command: "",
  //           lib: "",
  //           paramter: {},
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   name: "导调",
  //   icon: "",
  //   type: "page",
  //   groups: []
  // },
  // {
  //   name: "面板与标绘",
  //   icon: "",
  //   type: "page",
  //   groups: [
  //     {
  //       name: "标绘图层",
  //       icon: "",
  //       type: "group",
  //       items: [
  //         {
  //           name: "军标面板",
  //           icon: "",
  //           type: "button",
  //           enable: true,
  //           checked: false,
  //           command: "OpenWidgetCommand", // 打开一个组件
  //           lib: "WidgetPlugin",
  //           paramter: {
  //             styles: "bottom:20px;right:20px;",
  //             comName: "ExamplePanel",
  //           }
  //         }
  //       ],
  //     },
  //     {
  //       name: "军标标绘",
  //       icon: "",
  //       type: "group",
  //       items: [
  //         {
  //           name: "军标面板",
  //           icon: "",
  //           type: "button",
  //           enable: true,
  //           checked: false,
  //           command: "OpenWidgetCommand", // 打开一个组件
  //           lib: "WidgetPlugin",
  //           paramter: {
  //             styles: "bottom:20px;right:20px;",
  //             comName: "ExamplePanel",
  //           }
  //         },
  //         {
  //           name: "标绘属性",
  //           icon: "",
  //           type: "button",
  //           enable: true,
  //           checked: false,
  //           command: "OpenWidgetCommand", // 打开一个组件
  //           lib: "WidgetPlugin",
  //           paramter: {
  //             styles: "bottom:20px;right:20px;",
  //             comName: "ExamplePanel",
  //           }
  //         },
  //       ],
  //     },
  //   ]
  // }
  // {
  //       name: "雷达",
  //       icon: "",
  //       type: "page",
  //       groups: [
  //           {
  //               name: "常规",
  //               icon: "",
  //               type: "group",
  //               items: [
  //                   {
  //                       name: "添加",
  //                       img: "",
  //                       type: "button",
  //                       tip: "添加",
  //                       enable: true,
  //                       checked: false,
  //                       command: "RadarAddCommand",
  //                       lib: "RadarPlugin",
  //                       paramter: {},
  //                   },
  //                   // {
  //                   //     name: "配置",
  //                   //     img: "",
  //                   //     type: "button",
  //                   //     tip: "配置",
  //                   //     enable: true,
  //                   //     checked: false,
  //                   //     command: "",
  //                   //     lib: "",
  //                   //     paramter: {},
  //                   // },
  //               ],
  //           },
  //           // {
  //           //     name: "雷达",
  //           //     icon: "",
  //           //     type: "group",
  //           //     items: [
  //           //         {
  //           //             name: "无干扰",
  //           //             icon: "",
  //           //             type: "button",
  //           //             tip: "无干扰",
  //           //             enable: true,
  //           //             checked: false,
  //           //             command: "",
  //           //             lib: "",
  //           //             paramter: {
  //           //                 comName: "",
  //           //             },
  //           //         },
  //           //         {
  //           //             name: "组网",
  //           //             icon: "",
  //           //             type: "button",
  //           //             tip: "组网",
  //           //             enable: true,
  //           //             checked: false,
  //           //             command: "",
  //           //             lib: "",
  //           //             paramter: {
  //           //                 comName: "",
  //           //             },
  //           //         },
  //           //         {
  //           //             name: "动画",
  //           //             icon: "",
  //           //             type: "button",
  //           //             tip: "动画",
  //           //             enable: true,
  //           //             checked: false,
  //           //             command: "",
  //           //             lib: "",
  //           //             paramter: {
  //           //                 comName: "",
  //           //             },
  //           //         },
  //           //     ],
  //           // },
  //       ],
  //   },
];

export default config;
